apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-assets
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location ~ ^/rushmini/assets/(.*)$ {
            alias  /usr/share/nginx/html/$1;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }