apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-assets
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location ~ ^/rushmini/assets/(.*)$ {
            alias  /usr/share/nginx/html/$1;
            index  index.html index.htm;
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
            add_header Access-Control-Allow-Headers "Accept, X-Access-Token, X-Application-Name, X-Request-Sent-Time";
            add_header Access-Control-Allow-Credentials true;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }