{{- if .Values.pv.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-storage-claim
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pv.capacity | quote }}
  storageClassName: {{ .Values.pv.storageClassName | quote }}
{{- end -}}