apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rushmini-assets
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-rushmini-assets
  ports:
    - name: {{ .Release.Name }}-rushmini-assets
      port: 80