apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-assets
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-assets
  ports:
    - name: {{ .Release.Name }}-assets
      port: 80